### ISSUE TITLE
vagrant boxes appear to not be copied to o3 fast enough

### ISSUE THREAD

**Issue by dcermak** [os-autoinst/openqa-trigger-from-obs#93]
The vagrant openQA test suite appears to frequently fail due to it not being able to download the latest vagrant boxes from the backend (see for example https://openqa.opensuse.org/tests/1385878#step/tumbleweed/28). Unfortunately this does not happen every time, but out of the last three snapshots, it happened twice.

Could this be caused by the synchronization script?

**Comment by Martchus** [comment]
Looks line an instance of https://progress.opensuse.org/issues/69475 - so tests should not depend on `/var/lib/openqa/share` being mounted on the worker.

**Comment by dcermak** [comment]
Uh, ok. That's very unfortunate as I absolutely need that file to be available on the worker, otherwise the whole test cannot run.

**Comment by Martchus** [comment]
I've created https://github.com/os-autoinst/os-autoinst/pull/1527 to fix this. Since the problem has very likely nothing to do with the scripts within this repository I'm closing the issue here.
