### ISSUE TITLE
read_files.sh only works when deployed

### ISSUE THREAD

**Issue by Vogtinator** [os-autoinst/openqa-trigger-from-obs#96]
read_files.sh has an incorrect path to `rsync.secret` and assumes that the calling user is called `geekotest`.

It needs to use `geekotest@obspublish::openqa` and `__envdir/../../../rsync.secret` instead to work properly outside of the production environment.

**Comment by andrii-suse** [comment]
For testing and manual execution a workaround can be just export the password with `export RSYNC_PASSWORD=xxxxxxx` .
If that is not enough - one can create/link rsync.secret file inside t/ folder (and adjust .gitignore if needed)
I am not sure how to do it more convenient, so will close the call, assuming that workarounds above solve it
